= Social Anxiety cripples me. Here's my story.
:hp-image: http://ununsplash.imgix.net/photo-1423753623104-718aaace6772?q=75&fm=jpg&s=1ffa61419561b5c796bca3158e7c704c



Who am I?
---------

I'm not one of those perfect bloggers who are happy in life and who know it all. I'm someone who is not happy all the time. My mood swings like a pendulum. Stress, happiness, feeling of faliure haunt me. But I don't want to give up hope just yet. Hope and love are the two things that keep us alive. Money helps too but not as much as hope and love. 


My answer to 'How are you?'
---------------------------

I'm lonely, I have no friends where I live. I went to a boarding school on a mountain and then to a school in a big city and finally to a college in a village, near a big city. The school that I went to was posh. My dad couldn't afford it and I wasn't a good student. All this was a bad combination because my parents shared all their anger and frustration with me by saying things that pierced through my heart. I was and still am overweight. I think life gets better as we grow older. Mine surely has gotten better. As a kid I was bullied. I felt like a loser and that feeling has put a dent in my life which I'm still trying to fix. 

I would like to say to you as well as to me that, what we are today is a result of all the days that we have lived, suffered and ultimately prospered a bit. We can change ourselves one day at a time. Habits help us make that change. I can be who I want to be. But at the same time I should know that I am okay now and I deserve love and respect from not only others but from myself too. 


My parents
----------

My parents are really good people but they are not good parents. They love me beyond any measure but that's not enough. As a kid growing up it was difficult to spot that love. If they say things like they have spent ALL their hard earned money on me and that I've no good results to show and that I don't study... It hurts. But now in my 20s, I understand them. They are awesome and they have sacrificed a lot for me and I shall forever be thankful for that. I've learnt that they are people too and they were not able to deal with a kid having ADHD. In a third world country people don't care until you're really crazy! A kid is disciplined by spanking and it's considered normal. I was beaten by things like cricket bat, leather belt, cloth hanger, comb, burned with a hot spatula. All this violence didn't help at all. My parents were violent because they couldn't get me to do things that they wanted, thing that they thought were good for me. I forgive them.



Self Acceptance = Not hating
----------------------------

I have a friend who hates herself. I feel sorry for her and I try hard to give her as much love and affection as I can. What I do for her is not powerful at all, it won't make her life any better. Yes, maybe for a moment she'll feel better but after that she returns to hating herself. My kind words are just a distraction for her. What makes us happy is self acceptance. Yes we worry about what others think of us but we can fight that later. If you love yourself for who you are, life becomes a lot easier. The best way I've found to accept myself as I am is by self-talk. Yes, I talk to myself. I ask myself "how are you?" And I let myself reply to the question as if there are two parts of me. And in reality we all are made up of two parts which I call inner and outer. The outer part is for the world and the inner part is who we really are. There needs to be some communication between these two parts so that we don't lose ourselves. The outer part is simply the reflection of what people want me to be. The inner part is me.



Money
-----

I want to do so many things in life but everything involves money. I don't want to do something I don't like. It'll mean wasting my life. I've googled how to make $100 a month so that I can buy a macbook on EMI. Having a MacBook will help me in making music as well as in being a mobile app developer.


My mission
----------

I think if I can find a way to happiness then I can guide others through that way and maybe ask for a donation. So many people have money but happiness cannot be bought. If people share what they have be it money, love, happiness... It can makes them feel better. There are so many cool people who have dedicated their life in doing what they love. If one can do that and others appreciate their work then they it leads to them finding meaning in their work. Ofcourse life is easier but being happy is a state of mind.

I don't want to live in the shadow of my past. I want to build a better future for myself. I've started my journey and you are most welcome to join me :)

On this blog, I share with you my life, things that work for me and the approach I take to be happy and successful in life.


Thanks for your your time. While you're still reading this, I hope for you that everything falls into place and that you be happy.

****
I was in the flow so I wrote everything that was on my mind. I'll edit it over time. You could help me by sending any errors you find here to author@allalone.me or in the comments.
****